# Build options
[buildOptions]
optimizeWithTtx = false

[buildPlans.IosevkaToaq]
family = "Iosevka Toaq"
desc = "Monospace"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true
buildCharMap = true
snapshotFamily = 'Iosevka Toaq'
snapshotFeature = {"NWID" = 1}

[buildPlans.IosevkaToaqSlab]
family = "Iosevka Toaq Slab"
desc = "Monospace, slab-serif"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = true
buildCharMap = true
snapshotFamily = 'Iosevka Toaq Slab'
snapshotFeature = {"NWID" = 1}

[buildPlans.IosevkaToaqAile]
family = "Iosevka Toaq Aile"
desc = "Quasi-proportional"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = true
buildCharMap = true
snapshotFamily = 'Iosevka Toaq Aile'
snapshotFeature = {"NWID" = 0}

[buildPlans.IosevkaToaqAile.variants.design]
capital-i = "serifless"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-w = "straight-flat-top-serifless"
a = "double-storey-serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless"
i = "serifless"
j = "flat-hook-serifless"
k = "straight-serifless"
l = "serifless"
r = "compact-serifless"
t = "flat-hook"
u = "toothed-serifless"
w = "straight-flat-top-serifless"
y = "straight-serifless"
long-s = "flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-iota = "flat-tailed"
lower-lambda = "straight-turn"
lower-tau = "short-tailed"
cyrl-a = "double-storey-serifless"
cyrl-u = "straight-serifless"
cyrl-ef = "split-serifless"
four = "closed-serifless"
six = "closed-contour"
nine = "closed-contour"
brace = "straight"
guillemet = "straight"
at = "fourfold"
percent = "rings-continuous-slash"
micro-sign = "toothed-serifless"

# Letterform control for U+1D670 ... U+1D6A3
[buildPlans.IosevkaToaqAile.derivingVariants.mathtt.design]
capital-i = "serifed"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-w = "straight-flat-top-serifless"
a = "double-storey-serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless"
i = "serifed"
j = "flat-hook-serifed"
k = "straight-serifless"
l = "serifed"
r = "compact-serifless"
t = "flat-hook"
u = "toothed-serifless"
w = "straight-flat-top-serifless"
y = "straight-serifless"
long-s = "flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-iota = "serifed-flat-tailed"
lower-lambda = "straight-turn"
lower-tau = "short-tailed"
cyrl-a = "double-storey-serifless"
cyrl-u = "straight-serifless"
cyrl-ef = "split-serifless"
four = "closed-serifless"
six = "closed-contour"
nine = "closed-contour"
brace = "straight"
guillemet = "straight"
at = "fourfold"
percent = "rings-continuous-slash"
micro-sign = "toothed-serifless"

[buildPlans.IosevkaToaqAile.widths.Normal]
shape = 600
menu  = 5
css   = "normal"

[buildPlans.IosevkaToaqEtoile]
family = "Iosevka Toaq Etoile"
desc = "Quasi-proportional, slab-serif"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = true
buildCharMap = true
snapshotFamily = 'Iosevka Toaq Etoile'
snapshotFeature = {"NWID" = 0}

[buildPlans.IosevkaToaqEtoile.variants.design]
capital-m = "flat-bottom-serifed"
capital-w = "straight-flat-top-serifed"
f = "flat-hook-serifed"
i = "serifed"
j = "flat-hook-serifed"
l = "serifed"
t = "flat-hook"
w = "straight-flat-top-serifed"
long-s = "flat-hook-bottom-serifed"
eszet = "longs-s-lig-bottom-serifed"
lower-iota = "serifed-flat-tailed"
lower-tau = "short-tailed"
cyrl-ef = "split-serifed"
four = "closed-serifed"
six = "closed-contour"
nine = "closed-contour"
brace = "straight"
guillemet = "straight"
at = "fourfold"
percent = "rings-continuous-slash"

[buildPlans.IosevkaToaqEtoile.variants.italic]
f = "flat-hook-tailed"
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
w = "straight-flat-top-motion-serifed"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed-serifless"
cyrl-ef = "split-cursive"

[buildPlans.IosevkaToaqEtoile.widths.Normal]
shape = 600
menu  = 5
css   = "normal"

###################################################################################################
# Collect plans

[collectPlans.IosevkaToaq]
release = true
from = [
	"IosevkaToaq",
	"IosevkaToaqSlab",
	"IosevkaToaqAile",
	"IosevkaToaqEtoile"
]

###################################################################################################
# Weight mappings (style => shape weight, menu weight, CSS weight)
#   Shape weight : affects the shape of the glyphs
#   Menu weight  : affects the font menu name
#   CSS weight   : affects the webfont CSS "font-weight" property
# IMPORTANT : Currently "menu" property only support 100, 200, 300, 350, 400, 450, 500, 600, 700,
#             800, 900, and "shape" properly only supports number between 100 and 900 (inclusive).

[weights.Thin]
shape = 100
menu  = 100
css   = 100

[weights.ExtraLight]
shape = 200
menu  = 200
css   = 200

[weights.Light]
shape = 300
menu  = 300
css   = 300

[weights.Regular]
shape = 400
menu  = 400
css   = 400

[weights.Medium]
shape = 500
menu  = 500
css   = 500

[weights.SemiBold]
shape = 600
menu  = 600
css   = 600

[weights.Bold]
shape = 700
menu  = 700
css   = 700

[weights.ExtraBold]
shape = 800
menu  = 800
css   = 800

[weights.Heavy]
shape = 900
menu  = 900
css   = 900

# slope mappings (style => slope angle, shape slope grade, menu slope, CSS slope)
[slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

# [slopes.Oblique]
# angle = 9.4
# shape = "oblique"
# menu  = "oblique"
# css   = "oblique"

# [slopes.Italic]
# angle = 9.4
# shape = "italic"
# menu  = "italic"
# css   = "italic"

# Width mappings (style => shape width, menu width, CSS stretch)
#   Shape width   : affects the shape of the glyphs
#   Menu width    : affects the font menu name
#   CSS stretch   : affects the webfont CSS "font-stretch" property
#
# IMPORTANT : Currently "shape" property only support 3 ... 9
#              and "menu" only support 1 ... 9

[widths.Normal]
shape = 500
menu  = 5
css   = "normal"

# [widths.Extended]
# shape = 600
# menu  = 7
# css   = "expanded"
