name: Build
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Build all fonts
        run: nix build .
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: latest
          prerelease: false
          files: 'result/share/fonts/*/*'
      - name: Push to fonts repository
        run: |
          git clone https://github.com/toaq/fonts.git
          cd fonts
          cp -R ../result/share/fonts/* .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Iosevka [skip ci]"
          git push https://x-access-token:${{ secrets.TOAQ_FONTS_PAT }}@github.com/toaq/fonts.git
